### ISSUE TITLE
SEGV in global destruction

### ISSUE THREAD

**Issue by andk** [preaction/List-Slice#1] opened 2015-05-26 10:50 UTC
Many perl versions segfault on the t/head-tail.t test.

http://matrix.cpantesters.org/?dist=List-Slice%200.002

Stack trace without debugging symbols:

(gdb) bt
#0  0x00000000004b72f6 in do_clean_named_objs ()
#1  0x00000000004b53d2 in S_visit ()
#2  0x00000000004b7560 in Perl_sv_clean_objs ()
#3  0x000000000043e6ab in perl_destruct ()
#4  0x000000000041fdb4 in main ()

If further info is required, please shout.

HTH&&Thanks,

**Comment by preaction** [comment] 2015-05-31 21:57
I'm unable to reproduce this one, but there are a lot of other segfaults on cpantesters that might be related. This one doesn't seem to be the one I'm trying to track down now, since this one is in global destruction, and the one I'm looking at seems to be me messing up the stack

**Comment by preaction** [comment] 2015-05-31 23:58
I might be wrong. My complete screwup of the stack could be having all kinds of far-reaching consequences. Now to see if I should add some asserts into perl itself to prevent this...

**Comment by preaction** [comment] 2015-06-08 20:17
Patches to perl sent. No segfaults or failure reports for the latest version so far (though some *BSDs haven't reported in yet). I'll close this provisionally, with hope. Thanks for the report!

**Closed as completed by preaction** 2015-06-08 20:17 UTC
